### ISSUE TITLE
How to open Pet Manager in Ark Dev Kit?

### ISSUE THREAD

**Issue by aneparaczki** [duncanas/arkmods#2]
Hey!

Hoping you would see this question: How do you open your pet manager from the Unreal Editor simulation ? That mod is the best, I'd like to extend it a bit :)

Can't seem to find a hotkey to open it :(

**Comment by duncanas** [comment]
I haven't looked at the code in a long time, but by default it replaces the standard whistle selection command shortcut. Default is the Apostrophe key.

**Comment by aneparaczki** [comment]
Yeah, turns out that key is not on Hungarian keyboards. Got it, thanks!

**Comment by aneparaczki** [comment]
Also I wanted to talk to you about using/updating your code is that okay?

**Comment by duncanas** [comment]
Yes. I've posted on the Ark community site that anybody is free to take my mods and branch this code to create a new mod. I am going to take another shot at getting everything setup again and maybe address some of the bugs and issues with Pet Manager and Pet Res.

If you have not done any modding for Ark be prepared for a very steep learning curve. A great resource is the discord channel for ark modding.

**Comment by aneparaczki** [comment]
Thank you very much, It indeed got a learning curve, but an excellent way to get used to c style memory management which I need a hard lecture on, as well as Unreal Engine :D

![image](https://user-images.githubusercontent.com/13316016/50791402-04808e00-12c2-11e9-829e-c43f08af369f.png)

(Sorry last bother) Is this the right way to cook PetManager?

**Comment by duncanas** [comment]
Has been a long time since I built it, but pretty sure you want to do "Cook Game Mod"

**Comment by aneparaczki** [comment]
Thought the same. It ended up not working at all and reseting my input, but I think now I know why.
